# Generated by Django 5.2 on 2025-06-11 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0004_remove_notification_is_read_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
