# Generated by Django 5.2 on 2025-08-25 20:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0005_delete_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Emisión'),
            preserve_default=False,
        ),
    ]
