# Generated by Django 5.2 on 2025-08-25 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0006_notification_issue_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='issue_date',
        ),
    ]
