# Generated by Django 5.2 on 2025-05-24 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0005_booking_category_notification_order_timeslot_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercontainsproduct',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='code',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
