# Generated by Django 5.2 on 2025-06-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0006_ordercontainsproduct_subtotal_alter_booking_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
