# Generated by Django 5.2.1 on 2025-05-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0006_ordercontainsproduct_subtotal_alter_booking_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='number',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.IntegerField(default=2),
        ),
    ]
