# Generated by Django 5.2 on 2025-06-04 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
        ('menu_app', '0007_rename_title_product_name_table_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='userrecievesnotification',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='product',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tablehastimeslot',
            name='table',
        ),
        migrations.RemoveField(
            model_name='tablehastimeslot',
            name='time_slot',
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.user'),
        ),
        migrations.RemoveField(
            model_name='userrecievesnotification',
            name='user',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
        migrations.DeleteModel(
            name='TableHasTimeSlot',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserRecievesNotification',
        ),
    ]
