# Generated by Django 5.2 on 2025-07-10 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_app', '0013_remove_booking_approved_by'),
        ('menu_app', '0009_alter_order_code_alter_order_state_alter_order_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='bookings_app.booking'),
        ),
    ]
