# Generated by Django 5.2 on 2025-08-31 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0010_alter_order_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dicount_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='on_promotion',
            field=models.BooleanField(default=False),
        ),
    ]
