# Generated by Django 5.2 on 2025-09-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0011_product_dicount_percentage_product_on_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('on_promotion', models.BooleanField(default=False)),
                ('dicount_percentage', models.IntegerField(default=0)),
                ('products', models.ManyToManyField(related_name='combos', to='menu_app.product')),
            ],
        ),
    ]
