# Generated by Django 5.2 on 2025-09-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0012_combo'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
