# Generated by Django 5.2 on 2025-09-13 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0013_combo_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderContainsCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('combo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu_app.combo')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_app.order')),
            ],
        ),
    ]
