# Generated by Django 5.2 on 2025-09-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0014_ordercontainscombo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
