# Generated by Django 5.2 on 2025-09-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0017_comborating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avarage_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
