# Generated by Django 5.2 on 2025-09-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0019_alter_rating_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='avarage_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
