# Generated by Django 5.2 on 2025-06-11 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_app', '0002_rename_tablehastimeslot_tabletimeslot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='table',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='table',
            name='is_reserved',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='end',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='is_full',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='start',
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings_app.timeslot'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BookingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings_app.booking')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings_app.table')),
            ],
        ),
    ]
