# Generated by Django 5.2 on 2025-06-11 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_app', '0005_timeslot_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tabletimeslot',
            options={'permissions': [('assign_tables_to_timeslots', 'Can assign tables to timeslots')], 'verbose_name_plural': 'Assign tables to time slots'},
        ),
        migrations.AlterUniqueTogether(
            name='tabletimeslot',
            unique_together={('table', 'time_slot')},
        ),
    ]
