# Generated by Django 5.2 on 2025-06-12 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_app', '0006_alter_tabletimeslot_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tabletimeslot',
            options={'verbose_name_plural': 'Assign tables to time slots'},
        ),
        migrations.AlterField(
            model_name='tabletimeslot',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings_app.table'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
