# Generated by Django 5.2 on 2025-06-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_app', '0007_alter_tabletimeslot_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='tables',
            field=models.ManyToManyField(to='bookings_app.table'),
        ),
        migrations.DeleteModel(
            name='TableTimeSlot',
        ),
    ]
