# Generated by Django 5.2 on 2025-06-14 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_app', '0008_timeslot_tables_delete_tabletimeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tables',
            field=models.ManyToManyField(to='bookings_app.table'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings_app.timeslot'),
        ),
        migrations.DeleteModel(
            name='BookingTable',
        ),
    ]
