# Generated by Django 5.2 on 2025-06-16 23:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_app', '0009_booking_tables_alter_booking_time_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='issue_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
