# Generated by Django 5.2 on 2025-06-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_app', '0011_alter_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
