# Generated by Django 5.2 on 2025-06-23 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_app', '0012_alter_table_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='approved_by',
        ),
    ]
